### ISSUE TITLE
MIME type is text/html

### ISSUE THREAD

**Issue by sjparkinson** [fastly/insights.js#41]
The `insights.js` file should be served with a valid javascript MIME type. I spotted this in the Firefox console.

> The script from “https://www.fastly-insights.com/insights.js?k=[...]” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.

The log also links to:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

**Comment by sjparkinson** [comment]
Humm, making the request via the terminal all looks okay:

```
$ http -p hH https://www.fastly-insights.com/insights.js?k=[...]
GET /insights.js?k=[...] HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: www.fastly-insights.com
User-Agent: HTTPie/1.0.2

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Age: 56561
Cache-Control: private, no-cache, no-store, max-age=0, must-revalidate
Connection: keep-alive
Content-Type: application/javascript; charset=utf-8
Date: Thu, 08 Aug 2019 09:00:53 GMT
ETag: "6abe8fcd7177d14467bd5a4aaaff7989"
Last-Modified: Fri, 26 Jul 2019 17:17:51 GMT
Strict-Transport-Security: max-age=86400; includeSubDomains
Via: 1.1 varnish
X-Cache: HIT
X-Cache-Hits: 542653
X-Served-By: cache-lcy19236-LCY
X-Timer: S1565254854.966200,VS0,VE0
accept-ranges: none
content-encoding: gzip
transfer-encoding: chunked
vary: accept-encoding
```

**Comment by sjparkinson** [comment]
Here's what I have from the request Firefox makes:

```
HTTP/1.1 204 No content
Connection: close
Server: Varnish
Retry-After: 0
Content-Type: text/html; charset=utf-8
Accept-Ranges: bytes
Date: Thu, 08 Aug 2019 09:02:15 GMT
Via: 1.1 varnish
X-Served-By: cache-lcy19266-LCY
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1565254935.302126,VS0,VE0
Strict-Transport-Security: max-age=86400; includeSubDomains
```

**Comment by sjparkinson** [comment]
So either prevent content sniffing, or change the MIME for the 204 response?

**Comment by phamann** [comment]
Thanks for reporting this @sjparkinson. As you have identified, this isn't on the normal JS path, but the `204` we return if the request is outside of the sample rate in our new `v2.0.0` canary. I will fix upstream and let you know here once resolved.
